Numpy Array Object (ndarray)
Two parts:
1. raw data
2. metadata

In [91]:
import numpy as np

a = np.arange(5)    # 1-D array
print(a, a.shape)

m = np.array([np.arange(5), np.arange(5)])    # 2-D array
print(m, m.shape)

n = np.array([np.arange(5), np.arange(5), np.arange(5)])    # 3-D array
print(n, n.shape)

d = np.arange(start=1, stop = 10, step = 2)
print(d, d.shape)

[0 1 2 3 4] (5,)
[[0 1 2 3 4]
 [0 1 2 3 4]] (2, 5)
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]] (3, 5)
[1 3 5 7 9] (5,)


In [41]:
# numpy numerical datatype: int(5), unit(4), float(3), bool, complex

a = np.arange(6.0)    # 1-D array
print(a, a.shape)

[0. 1. 2. 3. 4. 5.] (6,)


In [42]:
a = np.arange(-5)    # NOT PERMISSIBLE
print(a, a.shape)

[] (0,)


In [79]:
b = np.arange(7, dtype=np.complex128)    # complex64
print(b)

[0.+0.j 1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j]


In [77]:
import numpy as np
names = np.array(['nirmala', 'jane'], dtype='U10')    # S10 and U100
print(names)

['nirmala' 'jane']


In [78]:
flag = np.arange(2, dtype=np.bool)    # ONLY TWO INPUTS
print(flag)

[False  True]


In [80]:
integerNum = np.arange(7, dtype=np.uint16)    # 8, 32, 64
print(integerNum)

[0 1 2 3 4 5 6]


In [82]:
integerPlatfrm = np.arange(7, dtype=np.intp)    # 32 or 64
print(integerPlatfrm)

[0 1 2 3 4 5 6]


In [83]:
floatNum = np.arange(7, dtype=np.float16)    # 8, 16, 32, 64
print(floatNum)

[0. 1. 2. 3. 4. 5. 6.]


In [84]:
# creating record type
S

In [89]:
import numpy as np
t = np.dtype([('name', np.str_, 40), ('numitems', np.int32), ('price', np.float32)])
print(t)

[('name', '<U40'), ('numitems', '<i4'), ('price', '<f4')]


In [92]:
df = np.array(6)
print(df)

6


In [ ]:
sliced_a = a[1:, :, :2]  # From the second block onward, all rows, first two columns