In [5]:
import numpy as np
a = np.arange(9)
# slicing is done using [star:stop:step]
print(a[3:7])
print(a[:7:2])
print(a[::-1])

[3 4 5 6]
[0 2 4 6]
[8 7 6 5 4 3 2 1 0]


ARRAY SHAPES

In [9]:
# Row-major Order ('C')
# Column-major Order ('F')
# Fortran-style Order ('A')

e = np.array([[1, 2, 3], [4, 5, 6]])
flattened1 = e.ravel(order='C')

f = np.array([[1, 2, 3], [4, 5, 6]])
flattened2 = f.ravel(order='F')

g = np.array([[1, 2, 3], [4, 5, 6]])
flattened3 = g.ravel(order='A')

print(flattened1, "\n", flattened2, "\n", flattened3)

[1 2 3 4 5 6] 
 [1 4 2 5 3 6] 
 [1 2 3 4 5 6]
