# **Pandas Series**

***

### The **Series** is the primary building block of pandas. It represents a one-dimensional array-like set of values
### of a single data type.

### **Using python list and dictionaries**

In [3]:
import pandas as pd
s = pd.Series([1, 2, 3, 4, 5, 'a'])
s

0    1
1    2
2    3
3    4
4    5
5    a
dtype: object

In [4]:
s[5] # value at index label 3

'a'

In [31]:
s.index.dtype

dtype('int64')

In [32]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [36]:
s.values

array([1, 2, 3, 4, 5, 'a'], dtype=object)

In [46]:
s.shape

(6,)

In [47]:
s.size

6

In [48]:
len(s)

6

In [5]:
pd.Series([2]*5) # using shorthand for list creation

0    2
1    2
2    2
3    2
4    2
dtype: int64

In [33]:
# uisng string as list
h = pd.Series(list('abcdefg'))
h

0    a
1    b
2    c
3    d
4    e
5    f
6    g
dtype: object

In [34]:
h.index

RangeIndex(start=0, stop=7, step=1)

In [49]:
h.values

array(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype=object)

In [50]:
h.shape

(7,)

In [51]:
h.size

7

In [52]:
len(h)

7

In [77]:
# using two lists series
status = ['name', 'post', 'item', 'place', 'date']
value = ['xyz', 1234, 'courier', 'abc', '2088-09-08']
k = pd.Series(status, index=value)
k

xyz            name
1234           post
courier        item
abc           place
2088-09-08     date
dtype: object

In [45]:
k.index

Index(['xyz', 1234, 'courier', 'abc', '2088-09-08'], dtype='object')

In [44]:
k.values

array(['name', 'post', 'item', 'place', 'date'], dtype=object)

In [56]:
len(k)

5

In [54]:
k.shape

(5,)

In [55]:
k.size

5

In [79]:
# dynamic way of creating a pandas series
g = pd.Series(np.arange(1,10), index=list("abcdefghi"))
g

a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
i    9
dtype: int32

In [80]:
g.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], dtype='object')

In [81]:
g.values

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
g.head

<bound method NDFrame.head of a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
i    9
dtype: int32>

In [87]:
g.tail

<bound method NDFrame.tail of a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
i    9
dtype: int32>

In [82]:
g.shape

(9,)

In [94]:
# takes input normal row indexing way even if the indexs are in rows
g.take([1, 2, 8])

b    2
c    3
i    9
dtype: int32

In [83]:
g.size

9

In [84]:
len(g)

9

In [7]:
info = pd.Series({"name": "xyz",
           "post": 1234,
           "item": "courier",
           "place": "abc",
           "date": "2088-09-08" })
info # Note the way dict is formed into a series

name            xyz
post           1234
item        courier
place           abc
date     2088-09-08
dtype: object

In [8]:
info["item"] # accessing value of label "item"

'courier'

In [9]:
info.index

Index(['name', 'post', 'item', 'place', 'date'], dtype='object')

In [35]:
info.values

array(['xyz', 1234, 'courier', 'abc', '2088-09-08'], dtype=object)

In [57]:
info.shape

(5,)

In [58]:
info.size

5

In [59]:
len(info)

5

In [96]:
info.head(n=2)

name     xyz
post    1234
dtype: object

In [97]:
info.tail(n=2)

place           abc
date     2088-09-08
dtype: object

In [100]:
# operates row wise irespective of the row index
info.take([0,1,4])

name           xyz
post          1234
date    2088-09-08
dtype: object

### **Using Numpy functions**

In [25]:
import numpy as np
m = pd.Series(np.arange(0,6))
m

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int32

In [22]:
m.index

RangeIndex(start=0, stop=6, step=1)

In [60]:
m.values

array([0, 1, 2, 3, 4, 5])

In [61]:
m.shape

(6,)

In [62]:
m.size

6

In [63]:
len(m)

6

In [102]:
m.head(n=3)

0    0
1    1
2    2
dtype: int32

In [103]:
m.tail(n=3)

3    3
4    4
5    5
dtype: int32

In [105]:
m.take([0, 5])

0    0
5    5
dtype: int32

In [101]:
n = pd.Series(np.linspace(0, 9, 5)) # 5 is the number of elements made
n

0    0.00
1    2.25
2    4.50
3    6.75
4    9.00
dtype: float64

In [29]:
n.index.dtype

dtype('int64')

In [30]:
n.index

RangeIndex(start=0, stop=5, step=1)

In [37]:
n.values

array([0.  , 2.25, 4.5 , 6.75, 9.  ])

In [64]:
n.shape

(5,)

In [65]:
n.size

5

In [66]:
len(n)

5

In [27]:
# created random numbers
np.random.seed(12345)
f = pd.Series(np.random.normal(size=6))
f

0   -0.204708
1    0.478943
2   -0.519439
3   -0.555730
4    1.965781
5    1.393406
dtype: float64

In [17]:
f.index

RangeIndex(start=0, stop=6, step=1)

In [38]:
f.values

array([-0.20470766,  0.47894334, -0.51943872, -0.5557303 ,  1.96578057,
        1.39340583])

In [67]:
f.shape

(6,)

In [68]:
f.size

6

In [69]:
len(f)

6

### **Using the scalar value**

In [13]:
x = pd.Series(np.arange(0,5))
x*2

0    0
1    2
2    4
3    6
4    8
dtype: int32

In [18]:
x.index

RangeIndex(start=0, stop=5, step=1)

In [39]:
x.values

array([0, 1, 2, 3, 4])

In [70]:
x.shape

(5,)

In [71]:
x.size

5

In [72]:
len(x)

5

In [28]:
t = pd.Series((2,3, 4, 1, 0))
t

0    2
1    3
2    4
3    1
4    0
dtype: int64

In [73]:
t.shape

(5,)

In [74]:
t.size

5

In [75]:
len(t)

5

In [20]:
t.index

RangeIndex(start=0, stop=5, step=1)

In [40]:
t.values

array([2, 3, 4, 1, 0], dtype=int64)

***

## <span style="color:red">**red text**</span>

## <span style="font-family:Times New Roman">**red text**</span> **changed font.**